email: abhinavkaushlya@gmail.com
description: My experiences of GCI 2019.
baseurl: "/gci-blog-2019"
twitter_username: abhishalya
github_username:  abhishalya

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: pretty
